export interface ReleasePost {
  slug: string;
  title: string;
  date: string;
  tag: string;
  body: string;
  highlights: string[];
}

export const releaseNotes: ReleasePost[] = [
  {
    slug: 'february-2018-the-origin',
    title: 'The Origin',
    date: 'February 2018',
    tag: '',
    body: "zStudio began as a tool solving a very specific problem: game studios had years of valuable animation work locked inside Adobe Flash (.fla) files, and the web was moving to HTML5. Getting that work out — with all its animation tracks, sprite hierarchies, pivot points, and bitmap fonts intact — required something that didn't exist yet. So we built it ourselves. The first commit landed in February 2018. The core was an Adobe AIR application written in ActionScript 3. It accepted a compiled .swf file on the command line, walked the entire display list, and wrote out a structured placements.json alongside individual PNG images for every display object. That JSON schema — templates, instances, portrait/landscape orientation transforms, animation keyframes — became the foundation that zStudio is still built on today. By August 2018 the tool could pack all images into a single texture atlas using a custom rectangle packer written in AS3. Matrix decomposition was added so that Flash's internal transformation matrices could be broken back down into the x, y, rotation, scaleX, scaleY, skewX, and skewY values the runtime actually needed. A font exporter was built to extract embedded Flash fonts and convert them to bitmap font data. In September 2023 the placements.json output structure was tightened up. In February 2025 the project was overhauled, completely rewritten in TypeScript and detached from the Flash/AIR environment.",
    highlights: [
      'Adobe AIR / ActionScript 3 SWF-to-JSON exporter',
      'Custom rectangle packer and texture atlas builder',
      'Matrix decomposition for clean transform export (x, y, rotation, scale, skew)',
      'Font exporter and bitmap font pipeline',
      'placements.json schema — the scene format that underpins all of zStudio',
      'JSFL scripts for Adobe Animate pre-processing (timeline unification, library conversion, image export)',
      'Portrait/landscape dual-orientation support in the output format',
      'Rewritten as a TypeScript project in February 2025',
    ],
  },
  {
    slug: 'february-2025-the-first-lines',
    title: 'The First Lines',
    date: 'February 2025',
    tag: '',
    body: "zStudio's rebirth began in February 2025 with the first real commits. These early days were all about laying the foundation: setting up the Git repository properly, wiring together a basic Electron + PIXI.js canvas, and proving out the core loop of dragging images onto a stage and moving them around. By the end of the month we had a working grid canvas, rough copy/paste support, initial asset loading from disk, and the very first version of a \"library\" — a panel on the left that would eventually become the Templates panel. Nothing was pretty yet, but the bones were there.",
    highlights: [
      'Project bootstrapped with Electron + TypeScript + PIXI.js',
      'Basic stage canvas with grid overlay',
      'Copy/paste for stage assets (initial pass)',
      'Asset loading from local filesystem',
      'Library panel scaffold',
    ],
  },
  {
    slug: 'march-2025-building-the-editor',
    title: 'Building the Editor',
    date: 'March 2025',
    tag: '',
    body: "March was the single busiest month in zStudio's history — over 250 commits landed as the project went from rough prototype to a genuine editor. The application was officially renamed zStudio during this sprint. The core panel layout came together: a Hierarchy panel for the scene tree, a Properties/Attributes panel for inspecting assets, and a Timeline panel for animations. The editor gained its first proper text support, system font scanning, and a full text inspector. Drop shadow filters were added along with a Filters Inspector panel. Multi-select landed (hold Shift to select multiple assets). The first version of Undo/Redo shipped, backed by a proper UndoManager. Pivot point editing arrived with a dedicated PivotInspector. Packaging for macOS and Windows was wired up, including code signing for Mac.",
    highlights: [
      'App renamed to zStudio',
      'Hierarchy, Timeline, and Properties panels',
      'Text and font support with system font scanning',
      'Drop shadow filters (FiltersInspector)',
      'Multi-select with Shift-click',
      'Undo/Redo (UndoManager)',
      'Pivot point editing (PivotInspector)',
      'Image replace via file dialog',
      'Hot Keys panel',
      'About panel with version info',
      'Tabbed multi-canvas interface',
      'Animation system with keyframes and easing',
      'macOS code signing + Windows/Mac packaging scripts',
    ],
  },
  {
    slug: 'april-2025-timeline-and-templates',
    title: 'Timeline & Templates Polish',
    date: 'April 2025',
    tag: '',
    body: "April focused on deepening the animation and template systems. The SelectionManager was extracted as a dedicated module to manage drag targets cleanly across panels. Width and height input fields landed in the Transform Inspector, giving numeric control over asset dimensions. The Hierarchy panel gained drill-down navigation — double-clicking a container zooms you into it. Timeline got lock/unlock per layer and frame-management buttons. Duplicate template was added from the Properties panel. The first robot template assets appeared as bundled examples. The easing system was extended with an \"Apply to All\" button on the timeline, and the Copy/Paste Properties feature let you copy transform values between assets.",
    highlights: [
      'SelectionManager for multi-asset drag handling',
      'Width/height fields in Transform Inspector',
      'Drill-down into containers in Hierarchy panel',
      'Timeline lock/unlock per layer',
      'Duplicate template from Properties panel',
      '"Apply easing to all" button on Timeline',
      'Copy/paste transform properties between assets',
      'Undo for frame-based animation operations',
      'Example robot limb assets bundled',
    ],
  },
  {
    slug: 'may-2025-packaging-and-distribution',
    title: 'Packaging & Distribution',
    date: 'May 2025',
    tag: '',
    body: "May was a brief but important month focused on distribution. The Windows installer build (NSIS target) was set up. macOS notarization was tackled and finally succeeded. The build pipeline was overhauled to produce properly signed, packaged artifacts for both platforms. Very few feature commits — but this was the work that made zStudio something that could actually be handed to users.",
    highlights: [
      'Windows NSIS installer target',
      'macOS notarization (success!)',
      'Build pipeline hardening for distribution',
      'dotenv added for environment variable management',
    ],
  },
  {
    slug: 'june-2025-spine-particles-anchoring',
    title: 'Spine, Particles & Anchoring',
    date: 'June 2025',
    tag: 'v1.0.2',
    body: "June was a landmark month for asset type support. Spine animation landed — users can now import .json + .atlas Spine files and place animated characters on stage. Shortly after, Pixi Particle files became importable too, with a full particle controller and inspector. The Anchoring system was built from the ground up: assets can be anchored to edges or corners of the stage so they reposition correctly when the resolution or orientation changes. Cue points arrived in the Timeline — named markers you can drop on specific frames and reference at runtime. The ButtonInspector was added to configure button states. Alignment and distribution tools appeared in the Properties panel. The orientation management system let you define separate portrait and landscape transforms per asset.",
    highlights: [
      'Spine animation import (SpineController + SpineInspector)',
      'Particle system import (ParticleController + ParticleInspector)',
      'Anchoring system — pin assets to screen edges/corners',
      'Cue points in Timeline',
      'ButtonInspector for button states',
      'Alignment & distribution tools',
      'Portrait/landscape orientation per asset',
      'Welcome page with video tutorials',
      'macOS entitlements for sandboxing',
    ],
  },
  {
    slug: 'july-2025-scene-management-cross-scene-copy',
    title: 'Scene Management & Cross-Scene Copy',
    date: 'July 2025',
    tag: 'v1.0.8',
    body: "July brought six releases as the team shipped a steady stream of quality-of-life improvements. The headline feature was copying assets between scenes — you can now copy a selection in one scene and paste it into another open scene tab. The export pipeline was refactored around a typed ExportType interface, making the export menu cleaner and more extensible. A Name Change panel let users rename templates inline. The Top Menu gained an Exit option. Particle folder importing from the file menu was wired up.",
    highlights: [
      'Copy assets between open scene tabs',
      'ExportType interface for clean export menu',
      'NameChangePanel for renaming templates',
      'Exit option in Top Menu',
      'Particle folder import from file menu',
      'Pixi DevTools integration option',
      'macOS App Store entitlements cleaned up',
      'Welcome page video tutorials updated',
    ],
  },
  {
    slug: 'august-2025-webviews-and-undo-hardening',
    title: 'Webviews & Undo Hardening',
    date: 'August 2025',
    tag: 'v1.1.15',
    body: "August saw two phases. The first half was a rapid stabilisation sprint — undo coverage was extended to wrap/break/paste operations, texture atlas loading was improved, and multi-select pivot reset shipped. Then on August 17 came the biggest architectural change yet — the entire renderer was migrated to Electron webviews (v1.1.0). This unlocked proper process isolation and paved the way for the multi-scene tab experience. The rest of August hardened the new architecture: text JSON styling, Spine skin support, the welcome screen showing recently opened scenes with thumbnails, fixed library search, and improved texture atlas frame handling. On the runtime side, August also saw the launch of the first two companion importer packages: zImporter_PIXI7 and zImporter_Phaser — npm libraries developers can drop into their own games to load and display zStudio scenes at runtime.",
    highlights: [
      'v1.1.0: Full migration to Electron webviews',
      'Text JSON loading for dynamic text styles',
      'Spine skin support',
      'Undo for wrap, break, paste operations',
      'Welcome screen with recent scenes',
      'Fixed library panel search',
      'Texture atlas sequence frame aliasing',
      'Multi-select pivot reset',
      'zImporter_PIXI7: initial release',
      'zImporter_Phaser: initial release',
    ],
  },
  {
    slug: 'september-2025-tooltips-alignment-nine-slice',
    title: 'Tooltips, Alignment & Nine-Slice',
    date: 'September 2025',
    tag: 'v1.1.39',
    body: "September was a polish sprint with 23 releases. A comprehensive tooltip system was built — every button and control in the UI now shows a tooltip on hover. The Bottom Panel was introduced as a persistent bar for common actions like focusing on the stage. Alignment tools were improved with proper spacing calculations. Dynamic sliders replaced static sliders in the Filters and Text inspectors. Nine-slice support was fixed for proper inset propagation. The welcome screen got scene preview thumbnails from saved JSON. A SceneInspector was added for setting the scene FPS and resolution from the Properties panel. zImporter_PIXI7 received its first significant update: improved text handling, ZContainer resizing logic, and pivot behaviour on fit-to-screen.",
    highlights: [
      'Tooltips on all UI controls',
      'Bottom Panel (focus on stage, etc.)',
      'Dynamic sliders in Filters/Text Inspector',
      'Nine-slice fix',
      'Scene preview thumbnails on welcome screen',
      'SceneInspector (FPS + resolution controls)',
      'Improved cursor feedback throughout',
      'Resolution input fields added',
      'zImporter_PIXI7: improved text handling, ZContainer resizing, pivot fixes',
    ],
  },
  {
    slug: 'october-2025-z-index-and-spine-skins',
    title: 'Z-Index & Spine Skins',
    date: 'October 2025',
    tag: 'v1.1.43',
    body: "October was a quieter month — four releases — but they carried meaningful features. A ZIndexInspector was added to the Properties panel, letting you explicitly set the z-order of any asset. Spine skin switching at design time was wired up. A Scene Validation utility was introduced — when loading a scene, zStudio now reports any objects that are missing from or added to the saved data, so you catch schema drift early. GUI hover state was tracked in the Model to prevent accidental clicks when the cursor is over a panel.",
    highlights: [
      'ZIndexInspector panel',
      'Spine skin switching in SpineInspector',
      'Scene validation on load (missing/added objects report)',
      'GUI hover state tracking (no accidental canvas clicks)',
      'Line height property for text assets',
    ],
  },
  {
    slug: 'november-2025-hierarchy-drag-and-asset-locking',
    title: 'Hierarchy Drag & Asset Locking',
    date: 'November 2025',
    tag: 'v1.1.65',
    body: "November shipped an important workflow feature: drag-and-drop reordering in the Hierarchy panel. You can now drag any asset up or down in the tree to change its layer order or reparent it — no more relying solely on keyboard shortcuts. An asset locking mechanism was added: lock any asset to prevent accidental moves or edits. Name validation was tightened to prevent reserved words and duplicates. A default font system was built so your preferred font persists across sessions. The Electron version was pinned to v31.7.7 to preserve file drag-and-drop behaviour. zImporter_Phaser matured significantly during November, shipping its first working HTML example scene, NineSlice support, and a more capable ZContainer and ZButton.",
    highlights: [
      'Drag-and-drop in Hierarchy panel',
      'Asset locking (lock/unlock any asset)',
      'Name validation (reserved words, duplicates)',
      'Default font persistence',
      'Image replacement via file drag',
      'Electron pinned to v31.7.7',
      'zImporter_Phaser: first HTML example, NineSlice, ZButton/ZContainer improvements',
    ],
  },
  {
    slug: 'december-2025-gradient-text-bitmap-fonts-filters',
    title: 'Gradient Text, Bitmap Fonts & Filters',
    date: 'December 2025',
    tag: 'v1.1.86',
    body: "December was a feature-dense month. Gradient text fills arrived — a GradientSlider lets you set gradient stops directly in the Text Inspector. BitmapText became a first-class text type alongside PIXI.Text, with full alignment and anchor support. The Filters Inspector grew ColorMatrix and Blur filter controls. A Photoshop importer appeared in the Top Menu (early version). File drag-and-drop in the Text Inspector lets you drop a .json style file directly onto it. Memory management got a serious pass — destroyed drag targets, cleanup on panel close, GPU RenderTexture release, and event listener teardown were all fixed. The undo system was expanded to cover text style changes, asset renaming, and child index changes. The importers kept pace: zImporter_PIXI7 gained BitmapText and gradient text alongside a refactored ZButton and ZSlider. zImporter_Phaser shipped new components.",
    highlights: [
      'Gradient text (GradientSlider)',
      'BitmapText type (alongside PIXI.Text)',
      'ColorMatrix and Blur filters',
      'Google Analytics integration',
      'Photoshop importer (early version)',
      'JSON drag-and-drop in Text Inspector',
      'Memory management overhaul',
      'Undo for text styles, rename, z-order changes',
      'Focus on Stage button',
      'zImporter_PIXI7: BitmapText, gradient text, components update',
      'zImporter_Phaser: components update',
    ],
  },
  {
    slug: 'january-2026-search-tabs-server-validation',
    title: 'Search, Tabs & Server Validation',
    date: 'January 2026',
    tag: 'v1.2.00',
    body: "January brought usability upgrades to the core navigation experience. A search bar was added to the Hierarchy panel so you can filter the scene tree by name. Keyboard arrow navigation in the hierarchy let you move between assets without a mouse. The webview tab system was improved: tabs became drag-and-droppable to reorder them, the welcome tab prevented duplicates, and an About modal was embedded inline. The server validation system now shows a proper blocker modal when the app version is outdated. Full bitmap font support shipped — load .fnt files, preview them in the font dropdown, and export them correctly in the scene JSON.",
    highlights: [
      'Search bar in Hierarchy panel',
      'Keyboard navigation in Hierarchy (arrow keys)',
      'Drag-and-drop webview tabs',
      'Blocker modal for outdated app versions',
      'Full bitmap font support (.fnt files)',
      'Font preview in dropdown',
      'Animation type added to asset system',
      'Memory leak fixes in Timeline cleanup',
    ],
  },
  {
    slug: 'february-2026-ai-image-generation-and-linux',
    title: 'AI Image Generation & Linux',
    date: 'February 2026',
    tag: 'v1.2.25',
    body: "February was the month AI arrived in zStudio. OpenAI image generation was integrated — provide your API key in the settings and generate images directly from the AI Image Inspector panel. A Leonardo AI module was also built. Linux became a supported platform — the build pipeline now produces a Linux AppImage, complete with icon and auto-updater support. The Photoshop → zStudio converter was deepened: portrait/landscape layouts are handled separately and the converter now validates the directory structure and returns detailed error messages. Other highlights: unsaved changes are flagged in the tab title, an Import Instructions panel explains how to load each asset type, and scene preview thumbnails were saved alongside scene files for the welcome screen. The importer ecosystem had a massive February too: zImporter_PIXI7 gained Spine 4.x support, a new ZTimeline init API, progress callbacks on asset loading, and full JSDoc documentation. zImporter_Phaser shipped Spine integration via @esotericsoftware/spine-phaser, BitmapText, an improved ZNineSlice, and a ParticleConverter for adapting PIXI particle configs to Phaser. A brand-new package, zImporter_html, launched on February 24 — a plain-HTML/JS importer for projects that don't use any game framework.",
    highlights: [
      'AI image generation (OpenAI + Leonardo AI)',
      'Linux support (AppImage)',
      'Windows auto-updater fix',
      'Photoshop → zStudio converter improvements',
      'Unsaved changes indicator on tab title',
      'Import Instructions panel',
      'Timeline easing colour coding',
      'Scene preview thumbnails saved on disk',
      'Play-on-start property for Spine animations',
      'zImporter_PIXI7: Spine support, components update, ZTimeline, progress callbacks, JSDoc',
      'zImporter_Phaser: Spine (spine-phaser), BitmapText, ZNineSlice, ParticleConverter',
      'zImporter_html: initial release (v1.0.0)',
    ],
  },
  {
    slug: 'march-2026-auth-credits-visual-overhaul',
    title: 'Auth, Credits & Visual Overhaul',
    date: 'March 2026',
    tag: 'v1.2.48',
    body: "March delivered the authentication and monetisation infrastructure that would underpin the v2.0 launch. An email/password login system was built with an OAuth flow and a dedicated auth window. A credit system for AI image generation was integrated — buy credit packs, view your balance, and get appropriate error handling when credits run low. Support for GPT Image 1.5 and an updated Leonardo v2 API were added alongside the existing OpenAI pipeline. The UI got a comprehensive theme overhaul — new colour definitions in StyleUtils and a DefaultTheme centralised all colours, improving consistency across every panel. Axis-locking during drag (hold Shift to constrain to X or Y) shipped. The importer family grew in March: zImporter_PIXI8 was created — a new package targeting the PixiJS v8 API, launching immediately with all components. zImporter_PIXI7 gained skew transform properties in the data interfaces and scene disposal. A GitHub Actions CI workflow was also added for automated dist builds.",
    highlights: [
      'Email/password auth + OAuth',
      'Credit system for AI image generation (buy packs, view balance)',
      'GPT Image 1.5 + Leonardo v2 API',
      'Full UI theme overhaul (DefaultTheme + StyleUtils)',
      'FlashToOutput/AIR tool integration',
      'WebP export format',
      'Axis-locking during drag (Shift key)',
      'Font preview in text dropdown',
      'Password reset flow',
      'Scene thumbnail saving',
      'zImporter_PIXI8: initial release',
      'zImporter_PIXI7: skew properties, scene disposal, CI pipeline',
      'zImporter_html: scene destroy fix',
    ],
  },
  {
    slug: 'april-2026-v2-licences-kinematics-example-scenes',
    title: 'v2.0 — Licences, Kinematics & Example Scenes',
    date: 'April 2026',
    tag: 'v2.0.2',
    body: "April was the v2.0 major release. The headline change was a complete licensing and authentication overhaul: a LicenseFeaturesManager controls which features are enabled based on the user's plan (Community, Pro, etc.). Spine importer, Photoshop importer, and other premium features gate behind licence checks. Watermarking landed for Community-tier exports — PNG exports get a subtle watermark when you're on the free plan. Example scenes (slot machine, space shooter, wild west) were added to the welcome screen so new users have something to explore immediately. The v2.0 release also added direct links to all four importer packages from the zStudio menu. The importers themselves received maintenance and refactoring passes across zImporter_PIXI7, zImporter_Phaser, and zImporter_PIXI8.",
    highlights: [
      'v2.0 major release',
      'LicenseFeaturesManager — per-plan feature gating',
      'Watermark on Community-tier PNG exports',
      'Upgrade CTA modal',
      'Design partner authentication flow',
      'Example scenes on welcome screen',
      'zImporter menu links (Phaser, Pixi 7/8, HTML)',
      'Production build hardening (obfuscation, bytenode)',
      'zImporter_PIXI7, PIXI8, Phaser: maintenance and refactoring updates',
    ],
  },
  {
    slug: 'may-2026-mcp-server-and-ai-panel',
    title: 'MCP Server & AI Panel',
    date: 'May 2026',
    tag: 'v2.1.3',
    body: "May brought the most ambitious feature yet: MCP (Model Context Protocol) server integration. zStudio now exposes a full MCP server that AI assistants (like Claude) can connect to and drive the editor programmatically. Via MCP, an AI can create scenes, import assets, generate images, set properties, navigate orientation, and more. A companion AI panel was added to the editor UI — a chat-like interface where you can type requests and have the AI assistant execute them directly against the open scene. The MaskInspector arrived, letting you set a PIXI mask on any container. Collapsible inspector sections made the Properties panel far less cluttered. The BottomPanel was reorganised. All four importer packages received significant updates in May: zImporter_PIXI7 underwent a major Spine loading refactor with improved animation handling. Masking support landed across all four packages. zImporter_html gained cue point support — you can now listen for named timeline markers directly in plain-HTML projects. zImporter_PIXI8 published its first README.",
    highlights: [
      'MCP Server — AI can drive zStudio programmatically',
      'AI panel (chat interface in the editor)',
      'AI reference documentation (AiReference)',
      'MaskInspector (PIXI mask support)',
      'Collapsible inspector sections',
      'TitleInspector section headers',
      'Spine looping + play-on-start properties',
      'Bitmap text controls in AI tools',
      'Code obfuscation in production build',
      'zImporter_PIXI7: Spine loading overhaul, masking, play-on-start',
      'zImporter_Phaser: masking, Spine looping, transform synchronisation',
      'zImporter_html: masking, cue points, playOnStart/looping',
      'zImporter_PIXI8: masking, Spine looping, README published',
    ],
  },
  {
    slug: 'june-2026-stability-and-token-refresh',
    title: 'Stability & Token Refresh',
    date: 'June 2026',
    tag: 'v2.1.5',
    body: "June was focused on stability and hardening the features shipped in May. A silent JWT token refresh was implemented — when the credits-balance token expires in the background, zStudio silently re-authenticates so the user never hits a stale-token error. The search bar in the Hierarchy panel had a clickability regression that was fixed. Ongoing AI panel work continued.",
    highlights: [
      'Silent JWT re-authentication for stale credit-balance tokens',
      'Hierarchy search bar clickability fix',
      'AI panel ongoing improvements',
    ],
  },
];
